version: "3.8"

services:
  # Base de datos MongoDB
  mongo:
    image: mongo:8.0
    container_name: joinup-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - dokploy-network
    # No exponemos puerto públicamente, solo interno

  # Mongo Express - Administrador web de MongoDB
  mongo-express:
    image: mongo-express:1.0
    container_name: joinup-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_SITE_BASEURL: /
    depends_on:
      - mongo
    networks:
      - dokploy-network
    labels:
      # Traefik labels para Mongo Express en subdominio
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`mongo.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.mongo-express.entrypoints=websecure"
      - "traefik.http.routers.mongo-express.tls.certresolver=letsencrypt"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: joinup-backend
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/joinup?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: https://${MAIN_DOMAIN}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo
    networks:
      - dokploy-network
    labels:
      # Traefik labels para Backend API
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${MAIN_DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      # CORS headers
      - "traefik.http.middlewares.backend-cors.headers.accessControlAllowOriginList=https://${MAIN_DOMAIN}"
      - "traefik.http.middlewares.backend-cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.backend-cors.headers.accessControlAllowHeaders=Content-Type,Authorization,Cookie"
      - "traefik.http.middlewares.backend-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.backend.middlewares=backend-cors"

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: joinup-frontend
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: https://${MAIN_DOMAIN}
    depends_on:
      - backend
    networks:
      - dokploy-network
    labels:
      # Traefik labels para Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${MAIN_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      
volumes:
  mongo_data:

networks:
  dokploy-network:
    external: true
